import { Roboto } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient();

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "DUDU currency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      const queryClient = new QueryClient()
      <QueryClientProvider client={queryClient}>
        <body className={roboto.className}>{children}</body>
      </QueryClientProvider>
    </html>
  );
}
